// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// colprods_arma
arma::rowvec colprods_arma(NumericMatrix x);
RcppExport SEXP _colprods_colprods_arma(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(colprods_arma(x));
    return rcpp_result_gen;
END_RCPP
}
// colprods_rcpp
NumericVector colprods_rcpp(NumericMatrix x);
RcppExport SEXP _colprods_colprods_rcpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(colprods_rcpp(x));
    return rcpp_result_gen;
END_RCPP
}
// colprods_rcpp_rowwise
NumericVector colprods_rcpp_rowwise(NumericMatrix x);
RcppExport SEXP _colprods_colprods_rcpp_rowwise(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(colprods_rcpp_rowwise(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_colprods_colprods_arma", (DL_FUNC) &_colprods_colprods_arma, 1},
    {"_colprods_colprods_rcpp", (DL_FUNC) &_colprods_colprods_rcpp, 1},
    {"_colprods_colprods_rcpp_rowwise", (DL_FUNC) &_colprods_colprods_rcpp_rowwise, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_colprods(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
