# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname colprods
#' @name colprods_arma
#' @title Calculate column products of a matrix
#' @description Various functions to calculate the column products of a matrix, each with
#'   a different implementation.
#' @param x a matrix
#' @example inst/examples/example-colprods.r
#' @export
colprods_arma <- function(x) {
    .Call(`_colprods_colprods_arma`, x)
}

#' @rdname colprods
#' @name colprods_rcpp
#' @export
colprods_rcpp <- function(x) {
    .Call(`_colprods_colprods_rcpp`, x)
}

#' @rdname colprods
#' @name colprods_rcpp_colwise
#' @export
colprods_rcpp_rowwise <- function(x) {
    .Call(`_colprods_colprods_rcpp_rowwise`, x)
}

